import { StateOfficials } from "@/lib/types";

export const stateOfficials: Record<string, StateOfficials> = {
  maryland: {
    name: "Maryland",
    slug: "maryland",
    abbreviation: "MD",
    governor: {
      id: "md-governor",
      name: "Governor Wes Moore",
      title: "Governor",
      state: "Maryland",
      stateSlug: "maryland",
      chamber: "executive",
      party: "Democratic",
      website: "https://governor.maryland.gov/",
      contactUrl: "https://governor.maryland.gov/contact-us/",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/c/c3/Wes_Moore_Official_Governor_Portrait.jpg",
    },
    senators: [
      {
        id: "md-sen-1",
        name: "Chris Van Hollen",
        title: "U.S. Senator",
        state: "Maryland",
        stateSlug: "maryland",
        chamber: "senate",
        party: "Democratic",
        website: "https://www.vanhollen.senate.gov/",
        contactUrl: "https://www.vanhollen.senate.gov/contact/email",
        photoUrl: "https://upload.wikimedia.org/wikipedia/commons/b/b2/Chris_Van_Hollen_official_portrait_115th_Congress.jpg",
      },
      {
        id: "md-sen-2",
        name: "Angela Alsobrooks",
        title: "U.S. Senator",
        state: "Maryland",
        stateSlug: "maryland",
        chamber: "senate",
        party: "Democratic",
        website: "https://www.alsobrooks.senate.gov/",
        contactUrl: "https://www.alsobrooks.senate.gov/contact/",
        photoUrl: "https://upload.wikimedia.org/wikipedia/commons/4/47/Sen._Angela_Alsobrooks_official_Senate_photo%2C_119th_Congress.jpg",
      },
    ],
    representatives: [
      {
        id: "md-rep-1",
        name: "Andy Harris",
        title: "U.S. Representative",
        state: "Maryland",
        stateSlug: "maryland",
        chamber: "house",
        district: "1st District",
        party: "Republican",
        website: "https://harris.house.gov/",
        contactUrl: "https://harris.house.gov/contact",
        photoUrl: "https://upload.wikimedia.org/wikipedia/commons/d/d1/Andy_Harris_115th_Congress_Higher_dif_%28cropped%29.jpg",
      },
      {
        id: "md-rep-2",
        name: "Johnny Olszewski",
        title: "U.S. Representative",
        state: "Maryland",
        stateSlug: "maryland",
        chamber: "house",
        district: "2nd District",
        party: "Democratic",
        website: "https://olszewski.house.gov/",
        contactUrl: "https://olszewski.house.gov/contact/",
        photoUrl: "https://upload.wikimedia.org/wikipedia/commons/6/66/Johnny_Olszewski_119th_congress.jpg",
      },
      {
        id: "md-rep-3",
        name: "Sarah Elfreth",
        title: "U.S. Representative",
        state: "Maryland",
        stateSlug: "maryland",
        chamber: "house",
        district: "3rd District",
        party: "Democratic",
        website: "https://elfreth.house.gov/",
        contactUrl: "https://elfreth.house.gov/address_authentication?form=/contact",
        photoUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e9/Representative_Sarah_Elfreth_Official_Portrait.jpg",
      },
      {
        id: "md-rep-4",
        name: "Glen Ivey",
        title: "U.S. Representative",
        state: "Maryland",
        stateSlug: "maryland",
        chamber: "house",
        district: "4th District",
        party: "Democratic",
        website: "https://ivey.house.gov/",
        contactUrl: "https://ivey.house.gov/address_authentication?form=/contact",
        photoUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e1/Rep._Glenn_Ivey_official_portrait%2C_118th_Congress.jpg",
      },
      {
        id: "md-rep-5",
        name: "Steny Hoyer",
        title: "U.S. Representative",
        state: "Maryland",
        stateSlug: "maryland",
        chamber: "house",
        district: "5th District",
        party: "Democratic",
        website: "https://hoyer.house.gov/",
        contactUrl: "https://hoyer.house.gov/address_authentication?form=/contact",
        photoUrl: "https://upload.wikimedia.org/wikipedia/commons/7/73/Steny_Hoyer_116th_Congress.jpg",
      },
      {
        id: "md-rep-6",
        name: "April McClain Delaney",
        title: "U.S. Representative",
        state: "Maryland",
        stateSlug: "maryland",
        chamber: "house",
        district: "6th District",
        party: "Democratic",
        website: "https://mcclaindelaney.house.gov/",
        contactUrl: "https://delaney.house.gov/address_authentication?form=/contact",
        photoUrl: "https://upload.wikimedia.org/wikipedia/commons/3/30/Rep._April_McClain_Delaney_Official_Portrait.jpg",
      },
      {
        id: "md-rep-7",
        name: "Kweisi Mfume",
        title: "U.S. Representative",
        state: "Maryland",
        stateSlug: "maryland",
        chamber: "house",
        district: "7th District",
        party: "Democratic",
        website: "https://mfume.house.gov/",
        contactUrl: "https://mfume.house.gov/address_authentication?form=/contact",
        photoUrl: "https://upload.wikimedia.org/wikipedia/commons/f/fd/Maryland_Congressman_Kweisi_Mfume%2C_117th_Congress.jpg",
      },
      {
        id: "md-rep-8",
        name: "Jamie Raskin",
        title: "U.S. Representative",
        state: "Maryland",
        stateSlug: "maryland",
        chamber: "house",
        district: "8th District",
        party: "Democratic",
        website: "https://raskin.house.gov/",
        contactUrl: "https://raskin.house.gov/address_authentication?form=/contact",
        photoUrl: "https://upload.wikimedia.org/wikipedia/commons/9/9b/Jamie_Raskin_Official_Portrait_2019.jpg",
      }
    ],
  },
   delaware: {
    name: "Delaware",
    slug: "delaware",
    abbreviation: "DE",
    governor: {
      id: "de-governor",
      name: "Governor Matt Meyer",
      title: "Governor",
      state: "Delaware",
      stateSlug: "delaware",
      chamber: "executive",
      party: "Democratic",
      website: "https://governor.delaware.gov/",
      contactUrl: "https://governor.delaware.gov/contact/",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/a/a6/%2802-19-2025%29_Matt_Meyer.jpg",
    },
    senators: [
      {
        id: "de-sen-1",
        name: "Chris Coons",
        title: "U.S. Senator",
        state: "Delaware",
        stateSlug: "delaware",
        chamber: "senate",
        party: "Democratic",
        website: "https://www.coons.senate.gov/",
        contactUrl: "https://www.coons.senate.gov/contact/share-your-opinion",
        photoUrl: "https://upload.wikimedia.org/wikipedia/commons/2/20/Chris_Coons_2024.jpg",
      },
      {
        id: "de-sen-2",
        name: "Lisa Blunt Rochester",
        title: "U.S. Senator",
        state: "Delaware",
        stateSlug: "delaware",
        chamber: "senate",
        party: "Democratic",
        website: "https://www.bluntrochester.senate.gov/",
        contactUrl: "https://www.bluntrochester.senate.gov/contact/",
        photoUrl: "https://upload.wikimedia.org/wikipedia/commons/8/82/Senator_Blunt_Rochester_Official_Portrait.jpg",
      },
      
    ],
    representatives: [
      {
        id: "de-rep-at-large",
        name: "Sarah McBride",
        title: "U.S. Representative",
        state: "Delaware",
        stateSlug: "delaware",
        chamber: "house",
        district: "At-Large",
        party: "Democratic",
        website: "https://mcbride.house.gov/",
        contactUrl: "https://mcbride.house.gov/contact/",
        photoUrl: "https://upload.wikimedia.org/wikipedia/commons/8/8a/Representative_Sarah_McBride_Official_Portrait.jpg",
      },
    ],
  },
  virginia: {
  name: "Virginia",
  slug: "virginia",
  abbreviation: "VA",

  governor: {
    id: "va-governor",
    name: "Governor Abigail Spanberger",
    title: "Governor",
    state: "Virginia",
    stateSlug: "virginia",
    chamber: "executive",
    party: "Democratic",
    website: "https://www.governor.virginia.gov/",
    contactUrl: "https://www.governor.virginia.gov/communicating-with-the-governors-office/",
    photoUrl: "https://www.governor.virginia.gov/media/governorvirginiagov/governor-of-virginia/images/Governor-Spanberger-Official-Portrait.jpg",
  },

  senators: [
    {
      id: "va-sen-1",
      name: "Mark Warner",
      title: "U.S. Senator",
      state: "Virginia",
      stateSlug: "virginia",
      chamber: "senate",
      party: "Democratic",
      website: "https://www.warner.senate.gov/",
      contactUrl: "https://www.warner.senate.gov/public/index.cfm?p=Contact",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/1/16/Mark_Warner_2025.jpg",
    },
    {
      id: "va-sen-2",
      name: "Tim Kaine",
      title: "U.S. Senator",
      state: "Virginia",
      stateSlug: "virginia",
      chamber: "senate",
      party: "Democratic",
      website: "https://www.kaine.senate.gov/",
      contactUrl: "https://www.kaine.senate.gov/contact",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/0/01/Tim_Kaine%2C_official_portrait_%28119th_Congress%29.jpg",
    },
  ],

  representatives: [
    {
      id: "va-rep-1",
      name: "Rob Wittman",
      title: "U.S. Representative",
      state: "Virginia",
      stateSlug: "virginia",
      chamber: "house",
      district: "1st District",
      party: "Republican",
      website: "https://wittman.house.gov/",
      contactUrl: "https://wittman.house.gov/contact/",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/4/4f/Rob_Wittman_official_portrait%2C_118th_Congress_%28cropped%29.jpg",
    },
    {
      id: "va-rep-2",
      name: "Jen Kiggans",
      title: "U.S. Representative",
      state: "Virginia",
      stateSlug: "virginia",
      chamber: "house",
      district: "2nd District",
      party: "Republican",
      website: "https://kiggans.house.gov/",
      contactUrl: "https://kiggans.house.gov/contact/",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/3/36/Kiggans_Jen_118th_Congress.jpg",
    },
    {
      id: "va-rep-3",
      name: "Bobby Scott",
      title: "U.S. Representative",
      state: "Virginia",
      stateSlug: "virginia",
      chamber: "house",
      district: "3rd District",
      party: "Democratic",
      website: "https://bobbyscott.house.gov/",
      contactUrl: "https://bobbyscott.house.gov/contact/",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/b/b5/BobbyScott.jpg",
    },
    {
      id: "va-rep-4",
      name: "Jennifer McClellan",
      title: "U.S. Representative",
      state: "Virginia",
      stateSlug: "virginia",
      chamber: "house",
      district: "4th District",
      party: "Democratic",
      website: "https://mcclellan.house.gov/",
      contactUrl: "https://mcclellan.house.gov/contact/",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/b/bf/U.S._Rep._Jennifer_McClellan_-_118th_Congress.jpg",
    },
    {
      id: "va-rep-5",
      name: "Bob Good",
      title: "U.S. Representative",
      state: "Virginia",
      stateSlug: "virginia",
      chamber: "house",
      district: "5th District",
      party: "Republican",
      website: "https://good.house.gov/",
      contactUrl: "https://good.house.gov/contact/",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/0/0b/Bob_Good_117th_U.S_Congress.jpg",
    },
    {
      id: "va-rep-6",
      name: "Ben Cline",
      title: "U.S. Representative",
      state: "Virginia",
      stateSlug: "virginia",
      chamber: "house",
      district: "6th District",
      party: "Republican",
      website: "https://cline.house.gov/",
      contactUrl: "https://cline.house.gov/contact/",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e3/Rep_Ben_Cline_Official_Photo_119th_Congress.jpg",
    },
    {
      id: "va-rep-7",
      name: "Eugene Vindman",
      title: "U.S. Representative",
      state: "Virginia",
      stateSlug: "virginia",
      chamber: "house",
      district: "7th District",
      party: "Democratic",
      website: "https://vindman.house.gov/",
      contactUrl: "https://vindman.house.gov/contact/",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/b/b0/Representative_Eugene_Vindman_Official_Portrait.jpg",
    },
    {
      id: "va-rep-8",
      name: "Don Beyer",
      title: "U.S. Representative",
      state: "Virginia",
      stateSlug: "virginia",
      chamber: "house",
      district: "8th District",
      party: "Democratic",
      website: "https://beyer.house.gov/",
      contactUrl: "https://beyer.house.gov/contact/",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/7/72/Rep._Don_Beyer%2C_official_portrait_%28118th_Congress%29.jpg",
    },
    {
      id: "va-rep-9",
      name: "Morgan Griffith",
      title: "U.S. Representative",
      state: "Virginia",
      stateSlug: "virginia",
      chamber: "house",
      district: "9th District",
      party: "Republican",
      website: "https://griffith.house.gov/",
      contactUrl: "https://griffith.house.gov/contact/",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/3/39/H._Morgan_Griffith_119th_Congress.jpg",
    },
    {
      id: "va-rep-10",
      name: "Suhas Subramanyam",
      title: "U.S. Representative",
      state: "Virginia",
      stateSlug: "virginia",
      chamber: "house",
      district: "10th District",
      party: "Democratic",
      website: "https://subramanyam.house.gov/",
      contactUrl: "https://subramanyam.house.gov/contact/",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/8/82/Subramayam_Suhas_119th_Congress_2.jpg",
    },
    {
      id: "va-rep-11",
      name: "Gerry Connolly",
      title: "U.S. Representative",
      state: "Virginia",
      stateSlug: "virginia",
      chamber: "house",
      district: "11th District",
      party: "Democratic",
      website: "https://connolly.house.gov/",
      contactUrl: "https://connolly.house.gov/contact/",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/b/b3/Gerry_Connolly_official_portrait_2022_%28cropped%29.jpg",
    },
  ],
},
pennsylvania: {
  name: "Pennsylvania",
  slug: "pennsylvania",
  abbreviation: "PA",

  governor: {
    id: "pa-governor",
    name: "Governor Josh Shapiro",
    title: "Governor",
    state: "Pennsylvania",
    stateSlug: "pennsylvania",
    chamber: "executive",
    party: "Democratic",
    website: "https://www.governor.pa.gov/",
    contactUrl: "https://www.governor.pa.gov/contact/",
    photoUrl: "https://upload.wikimedia.org/wikipedia/commons/2/26/Josh_Shapiro_December_2025.jpg",
  },

  senators: [
    {
      id: "pa-sen-1",
      name: "Bob Casey Jr.",
      title: "U.S. Senator",
      state: "Pennsylvania",
      stateSlug: "pennsylvania",
      chamber: "senate",
      party: "Democratic",
      website: "https://www.casey.senate.gov/",
      contactUrl: "https://www.casey.senate.gov/contact",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/3/30/Bob_Casey_Jr._official_photo.jpg",
    },
    {
      id: "pa-sen-2",
      name: "John Fetterman",
      title: "U.S. Senator",
      state: "Pennsylvania",
      stateSlug: "pennsylvania",
      chamber: "senate",
      party: "Democratic",
      website: "https://www.fetterman.senate.gov/",
      contactUrl: "https://www.fetterman.senate.gov/contact/",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/e/ea/John_Fetterman_official_portrait.jpg",
    },
  ],

  representatives: [
    {
      id: "pa-rep-1",
      name: "Brian Fitzpatrick",
      title: "U.S. Representative",
      state: "Pennsylvania",
      stateSlug: "pennsylvania",
      chamber: "house",
      district: "1st District",
      party: "Republican",
      website: "https://fitzpatrick.house.gov/",
      contactUrl: "https://fitzpatrick.house.gov/contact/",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/3/3a/Brian_Fitzpatrick_official_congressional_photo.jpg",
    },
    {
      id: "pa-rep-2",
      name: "Brendan Boyle",
      title: "U.S. Representative",
      state: "Pennsylvania",
      stateSlug: "pennsylvania",
      chamber: "house",
      district: "2nd District",
      party: "Democratic",
      website: "https://boyle.house.gov/",
      contactUrl: "https://boyle.house.gov/contact/",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/1/18/Brendan_Boyle%2C_official_portrait%2C_114th_Congress_%28cropped%29.jpg",
    },
    {
      id: "pa-rep-3",
      name: "Dwight Evans",
      title: "U.S. Representative",
      state: "Pennsylvania",
      stateSlug: "pennsylvania",
      chamber: "house",
      district: "3rd District",
      party: "Democratic",
      website: "https://evans.house.gov/",
      contactUrl: "https://evans.house.gov/contact/",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/c/c6/Rep._Dwight_Evans%2C_official_portrait%2C_118th_Congress.jpg",
    },
    {
      id: "pa-rep-4",
      name: "Madeleine Dean",
      title: "U.S. Representative",
      state: "Pennsylvania",
      stateSlug: "pennsylvania",
      chamber: "house",
      district: "4th District",
      party: "Democratic",
      website: "https://dean.house.gov/",
      contactUrl: "https://dean.house.gov/contact/",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/5/5a/Madeleine_Dean_Official_Portrait_116th_Congress.jpg",
    },
    {
      id: "pa-rep-5",
      name: "Mary Gay Scanlon",
      title: "U.S. Representative",
      state: "Pennsylvania",
      stateSlug: "pennsylvania",
      chamber: "house",
      district: "5th District",
      party: "Democratic",
      website: "https://scanlon.house.gov/",
      contactUrl: "https://scanlon.house.gov/contact/",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e3/Mary_Gay_Scanlon%2C_official_portrait%2C_2018_%283x4_cropped%29.jpg",
    },
    {
      id: "pa-rep-6",
      name: "Chrissy Houlahan",
      title: "U.S. Representative",
      state: "Pennsylvania",
      stateSlug: "pennsylvania",
      chamber: "house",
      district: "6th District",
      party: "Democratic",
      website: "https://houlahan.house.gov/",
      contactUrl: "https://houlahan.house.gov/contact/",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/2/2a/Houlahan_Chrissy_119th_Congress.jpg",
    },
    {
      id: "pa-rep-7",
      name: "Susan Wild",
      title: "U.S. Representative",
      state: "Pennsylvania",
      stateSlug: "pennsylvania",
      chamber: "house",
      district: "7th District",
      party: "Democratic",
      website: "https://wild.house.gov/",
      contactUrl: "https://wild.house.gov/contact/",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/d/d9/Susan_Wild%2C_Official_Portrait%2C_115th_Congress.jpg",
    },
    {
      id: "pa-rep-8",
      name: "Rob Bresnahan",
      title: "U.S. Representative",
      state: "Pennsylvania",
      stateSlug: "pennsylvania",
      chamber: "house",
      district: "8th District",
      party: "Republican",
      website: "https://bresnahan.house.gov/",
      contactUrl: "https://bresnahan.house.gov/contact/",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/2/27/Rep._Rob_Bresnahan_official_photo%2C_119th_Congress.jpg",
    },
    {
      id: "pa-rep-9",
      name: "Dan Meuser",
      title: "U.S. Representative",
      state: "Pennsylvania",
      stateSlug: "pennsylvania",
      chamber: "house",
      district: "9th District",
      party: "Republican",
      website: "https://meuser.house.gov/",
      contactUrl: "https://meuser.house.gov/contact/",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/1/15/Meuser_Dan_118th_Congress.jpg",
    },
    {
      id: "pa-rep-10",
      name: "Scott Perry",
      title: "U.S. Representative",
      state: "Pennsylvania",
      stateSlug: "pennsylvania",
      chamber: "house",
      district: "10th District",
      party: "Republican",
      website: "https://perry.house.gov/",
      contactUrl: "https://perry.house.gov/contact/",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/c/c0/Rep._Scott_Perry%2C_official_portrait%2C_118th_Congress.jpg",
    },
    {
      id: "pa-rep-11",
      name: "Lloyd Smucker",
      title: "U.S. Representative",
      state: "Pennsylvania",
      stateSlug: "pennsylvania",
      chamber: "house",
      district: "11th District",
      party: "Republican",
      website: "https://smucker.house.gov/",
      contactUrl: "https://smucker.house.gov/contact/",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/4/48/Lloyd_Smucker_Official_Congressional_Photo.jpg",
    },
    {
      id: "pa-rep-12",
      name: "Summer Lee",
      title: "U.S. Representative",
      state: "Pennsylvania",
      stateSlug: "pennsylvania",
      chamber: "house",
      district: "12th District",
      party: "Democratic",
      website: "https://lee.house.gov/",
      contactUrl: "https://lee.house.gov/contact/",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/8/8d/Rep._Summer_Lee_-_118th_Congress_%283x4_cropped%29.jpg",
    },
    {
      id: "pa-rep-13",
      name: "John Joyce",
      title: "U.S. Representative",
      state: "Pennsylvania",
      stateSlug: "pennsylvania",
      chamber: "house",
      district: "13th District",
      party: "Republican",
      website: "https://johnjoyce.house.gov/",
      contactUrl: "https://johnjoyce.house.gov/contact/",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/5/59/John_Joyce_119th_Congress.jpg",
    },
    {
      id: "pa-rep-14",
      name: "Guy Reschenthaler",
      title: "U.S. Representative",
      state: "Pennsylvania",
      stateSlug: "pennsylvania",
      chamber: "house",
      district: "14th District",
      party: "Republican",
      website: "https://reschenthaler.house.gov/",
      contactUrl: "https://reschenthaler.house.gov/contact/",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/0/0e/Guy_Reschenthaler_116th_Congress.jpg",
    },
    {
      id: "pa-rep-15",
      name: "Glenn Thompson",
      title: "U.S. Representative",
      state: "Pennsylvania",
      stateSlug: "pennsylvania",
      chamber: "house",
      district: "15th District",
      party: "Republican",
      website: "https://thompson.house.gov/",
      contactUrl: "https://thompson.house.gov/contact/",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/3/30/Glenn_Thompson_portrait_%28118th_Congress%29.jpg",
    },
    {
      id: "pa-rep-16",
      name: "Mike Kelly",
      title: "U.S. Representative",
      state: "Pennsylvania",
      stateSlug: "pennsylvania",
      chamber: "house",
      district: "16th District",
      party: "Republican",
      website: "https://kelly.house.gov/",
      contactUrl: "https://kelly.house.gov/contact/",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/1/19/Mike_Kelly_Photo.jpg",
    },
    {
      id: "pa-rep-17",
      name: "Chris Deluzio",
      title: "U.S. Representative",
      state: "Pennsylvania",
      stateSlug: "pennsylvania",
      chamber: "house",
      district: "17th District",
      party: "Democratic",
      website: "https://deluzio.house.gov/",
      contactUrl: "https://deluzio.house.gov/contact/",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/c/c0/Chris_Deluzio_119th_Congress.jpg",
    },
  ],
},
westvirginia: {
  name: "West Virginia",
  slug: "west-virginia",
  abbreviation: "WV",

  governor: {
    id: "wv-governor",
    name: "Governor Patrick Morrisey",
    title: "Governor",
    state: "West Virginia",
    stateSlug: "west-virginia",
    chamber: "executive",
    party: "Republican",
    website: "https://governor.wv.gov/",
    contactUrl: "https://governor.wv.gov/Pages/contact.aspx",
    photoUrl: "https://upload.wikimedia.org/wikipedia/commons/e/eb/Governor_Patrick_Morrisey_in_2025.jpg",
  },

  senators: [
    {
      id: "wv-sen-1",
      name: "Shelley Moore Capito",
      title: "U.S. Senator",
      state: "West Virginia",
      stateSlug: "west-virginia",
      chamber: "senate",
      party: "Republican",
      website: "https://www.capito.senate.gov/",
      contactUrl: "https://www.capito.senate.gov/contact/contact-form",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/7/75/Shelley_Moore_Capito_official_Senate_photo.jpg",
    },
    {
      id: "wv-sen-2",
      name: "Jim Justice",
      title: "U.S. Senator",
      state: "West Virginia",
      stateSlug: "west-virginia",
      chamber: "senate",
      party: "Republican",
      website: "https://www.justice.senate.gov/",
      contactUrl: "https://www.justice.senate.gov/contact-joe",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/3/3f/Senator_Jim_Justice_Official_Portrait.jpg",
    },
  ],

  representatives: [
    {
      id: "wv-rep-1",
      name: "Carol Miller",
      title: "U.S. Representative",
      state: "West Virginia",
      stateSlug: "west-virginia",
      chamber: "house",
      district: "1st District",
      party: "Republican",
      website: "https://miller.house.gov/",
      contactUrl: "https://miller.house.gov/contact/",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/5/5c/Carol_Miller%2C_official_portrait_%28118th_Congress%29.jpg",
    },
    {
      id: "wv-rep-2",
      name: "Riley Moore",
      title: "U.S. Representative",
      state: "West Virginia",
      stateSlug: "west-virginia",
      chamber: "house",
      district: "2nd District",
      party: "Republican",
      website: "https://rileymoore.house.gov/",
      contactUrl: "https://fileymoore.house.gov/contact/",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/f/f5/Moore_Riley_119th_Congress.jpg",
    },
  ],
},
"new-york": {
  name: "New York",
  slug: "new-york",
  abbreviation: "NY",

  governor: {
    id: "ny-governor",
    name: "Governor Kathy Hochul",
    title: "Governor",
    state: "New York",
    stateSlug: "new-york",
    chamber: "executive",
    party: "Democratic",
    website: "https://www.governor.ny.gov/",
    contactUrl: "https://www.governor.ny.gov/content/governor-contact-form",
    photoUrl: "https://upload.wikimedia.org/wikipedia/commons/8/8f/Governor_Kathy_Hochul_Press_Conference_%28cropped%29.jpg",
  },

  senators: [
    {
      id: "ny-sen-1",
      name: "Chuck Schumer",
      title: "U.S. Senator",
      state: "New York",
      stateSlug: "new-york",
      chamber: "senate",
      party: "Democratic",
      website: "https://www.schumer.senate.gov/",
      contactUrl: "https://www.schumer.senate.gov/contact/message-chuck",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/8/89/Chuck_Schumer_official_photo.jpg",
    },
    {
      id: "ny-sen-2",
      name: "Kirsten Gillibrand",
      title: "U.S. Senator",
      state: "New York",
      stateSlug: "new-york",
      chamber: "senate",
      party: "Democratic",
      website: "https://www.gillibrand.senate.gov/",
      contactUrl: "https://www.gillibrand.senate.gov/contact/email-me/",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/9/9a/Kirsten_Gillibrand%2C_official_photo%2C_116th_Congress.jpg",
    },
  ],

  representatives: [
    {
      id: "ny-rep-1",
      name: "Nick LaLota",
      title: "U.S. Representative",
      state: "New York",
      stateSlug: "new-york",
      chamber: "house",
      district: "1st District",
      party: "Republican",
      website: "https://lalota.house.gov/",
      contactUrl: "https://lalota.house.gov/contact/",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/5/5e/Nick_lalota_portrait.jpg",
    },
    {
      id: "ny-rep-2",
      name: "Andrew Garbarino",
      title: "U.S. Representative",
      state: "New York",
      stateSlug: "new-york",
      chamber: "house",
      district: "2nd District",
      party: "Republican",
      website: "https://garbarino.house.gov/",
      contactUrl: "https://garbarino.house.gov/contact/",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/6/66/Andrew_Garbarino_117th_U.S_Congress.jpg",
    },
    {
      id: "ny-rep-3",
      name: "Tom Suozzi",
      title: "U.S. Representative",
      state: "New York",
      stateSlug: "new-york",
      chamber: "house",
      district: "3rd District",
      party: "Democratic",
      website: "https://suozzi.house.gov/",
      contactUrl: "https://suozzi.house.gov/contact/email",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/9/90/TomSuozzi118thCongress.jpg",
    },
    {
      id: "ny-rep-4",
      name: "Laura Gillen",
      title: "U.S. Representative",
      state: "New York",
      stateSlug: "new-york",
      chamber: "house",
      district: "4th District",
      party: "Democratic",
      website: "https://gillen.house.gov/",
      contactUrl: "https://gillen.house.gov/contact/",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/9/95/Gillen_Laura_119th_Congress_%28cropped2%29.jpg",
    },
    {
      id: "ny-rep-5",
      name: "Gregory Meeks",
      title: "U.S. Representative",
      state: "New York",
      stateSlug: "new-york",
      chamber: "house",
      district: "5th District",
      party: "Democratic",
      website: "https://meeks.house.gov/",
      contactUrl: "https://meeks.house.gov/contact/",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/0/0f/Gregory_Meeks%2C_official_portrait%2C_115th_congress_%283x4_cropped%29.jpg",
    },
    {
      id: "ny-rep-6",
      name: "Grace Meng",
      title: "U.S. Representative",
      state: "New York",
      stateSlug: "new-york",
      chamber: "house",
      district: "6th District",
      party: "Democratic",
      website: "https://meng.house.gov/",
      contactUrl: "https://meng.house.gov/contact/",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/1/16/Grace_Meng_Official_Congressional_Photo.jpg",
    },
    {
      id: "ny-rep-7",
      name: "Nydia Velázquez",
      title: "U.S. Representative",
      state: "New York",
      stateSlug: "new-york",
      chamber: "house",
      district: "7th District",
      party: "Democratic",
      website: "https://velazquez.house.gov/",
      contactUrl: "https://velazquez.house.gov/contact/",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/f/f4/Nydia_Vel%C3%A1zquez_official_portrait.jpg",
    },
    {
      id: "ny-rep-8",
      name: "Hakeem Jeffries",
      title: "U.S. Representative",
      state: "New York",
      stateSlug: "new-york",
      chamber: "house",
      district: "8th District",
      party: "Democratic",
      website: "https://jeffries.house.gov/",
      contactUrl: "https://jeffries.house.gov/contact/",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/a/a6/Rep-Hakeem-Jeffries-Official-Portrait_%28cropped%29.jpg",
    },
    {
      id: "ny-rep-9",
      name: "Yvette Clarke",
      title: "U.S. Representative",
      state: "New York",
      stateSlug: "new-york",
      chamber: "house",
      district: "9th District",
      party: "Democratic",
      website: "https://clarke.house.gov/",
      contactUrl: "https://clarke.house.gov/contact/",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/4/49/Yvette_Clarke_official_photo.jpg",
    },
    {
      id: "ny-rep-10",
      name: "Dan Goldman",
      title: "U.S. Representative",
      state: "New York",
      stateSlug: "new-york",
      chamber: "house",
      district: "10th District",
      party: "Democratic",
      website: "https://goldman.house.gov/",
      contactUrl: "https://goldman.house.gov/contact/",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/0/0b/Dan_Goldman%2C_official_portrait_%28119th_Congress%29_%281%29.jpg",
    },
    {
      id: "ny-rep-11",
      name: "Nicole Malliotakis",
      title: "U.S. Representative",
      state: "New York",
      stateSlug: "new-york",
      chamber: "house",
      district: "11th District",
      party: "Republican",
      website: "https://malliotakis.house.gov/",
      contactUrl: "https://malliotakis.house.gov/contact/",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/9/94/Congresswoman_Nicole_Malliotakis.jpg",
    },
    {
      id: "ny-rep-12",
      name: "Jerry Nadler",
      title: "U.S. Representative",
      state: "New York",
      stateSlug: "new-york",
      chamber: "house",
      district: "12th District",
      party: "Democratic",
      website: "https://nadler.house.gov/",
      contactUrl: "https://nadler.house.gov/contact/",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/b/bb/Jerry_Nadler_116th_Congress_official_portrait_%28cropped%29.jpg",
    },
    {
      id: "ny-rep-13",
      name: "Adriano Espaillat",
      title: "U.S. Representative",
      state: "New York",
      stateSlug: "new-york",
      chamber: "house",
      district: "13th District",
      party: "Democratic",
      website: "https://espaillat.house.gov/",
      contactUrl: "https://espaillat.house.gov/contact/",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/a/aa/Rep._Adriano_Espaillat_117th_Official_Photo.jpg",
    },
    {
      id: "ny-rep-14",
      name: "Alexandria Ocasio-Cortez",
      title: "U.S. Representative",
      state: "New York",
      stateSlug: "new-york",
      chamber: "house",
      district: "14th District",
      party: "Democratic",
      website: "https://ocasio-cortez.house.gov/",
      contactUrl: "https://ocasio-cortez.house.gov/contact/",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/4/4a/Alexandria_Ocasio-Cortez_Official_Portrait.jpg",
    },
    {
      id: "ny-rep-15",
      name: "Ritchie Torres",
      title: "U.S. Representative",
      state: "New York",
      stateSlug: "new-york",
      chamber: "house",
      district: "15th District",
      party: "Democratic",
      website: "https://ritchietorres.house.gov/",
      contactUrl: "https://ritchietorres.house.gov/contact/",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/8/8a/Ritchie_Torres_117th_U.S_Congress.jpg",
    },
    {
      id: "ny-rep-16",
      name: "George Latimer",
      title: "U.S. Representative",
      state: "New York",
      stateSlug: "new-york",
      chamber: "house",
      district: "16th District",
      party: "Democratic",
      website: "https://latimer.house.gov/",
      contactUrl: "https://latimer.house.gov/contact/",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/a/ac/Latimer_George_119th_Congress_2.jpg",
    },
    {
      id: "ny-rep-17",
      name: "Mike Lawler",
      title: "U.S. Representative",
      state: "New York",
      stateSlug: "new-york",
      chamber: "house",
      district: "17th District",
      party: "Republican",
      website: "https://lawler.house.gov/",
      contactUrl: "https://lawler.house.gov/contact/",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/7/77/Rep._Mike_Lawler_official_photo.jpg",
    },
    {
      id: "ny-rep-18",
      name: "Pat Ryan",
      title: "U.S. Representative",
      state: "New York",
      stateSlug: "new-york",
      chamber: "house",
      district: "18th District",
      party: "Democratic",
      website: "https://patryan.house.gov/",
      contactUrl: "https://patryan.house.gov/contact/",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/a/a8/Pat_Ryan_117th_Congress_portrait.jpeg",
    },
    {
      id: "ny-rep-19",
      name: "Josh Riley",
      title: "U.S. Representative",
      state: "New York",
      stateSlug: "new-york",
      chamber: "house",
      district: "19th District",
      party: "Democratic",
      website: "https://riley.house.gov/",
      contactUrl: "https://riley.house.gov/contact/",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e2/Rep._Josh_Riley_official_photo%2C_119th_Congress.jpg",
    },
    {
      id: "ny-rep-20",
      name: "Paul Tonko",
      title: "U.S. Representative",
      state: "New York",
      stateSlug: "new-york",
      chamber: "house",
      district: "20th District",
      party: "Democratic",
      website: "https://tonko.house.gov/",
      contactUrl: "https://tonko.house.gov/contact/",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/4/4a/Paul_Tonko_118th_Congress.jpeg",
    },
    {
      id: "ny-rep-21",
      name: "Elise Stefanik",
      title: "U.S. Representative",
      state: "New York",
      stateSlug: "new-york",
      chamber: "house",
      district: "21st District",
      party: "Republican",
      website: "https://stefanik.house.gov/",
      contactUrl: "https://stefanik.house.gov/contact/",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/b/ba/Elise_Stefanik%2C_115th_official_photo_%284x5_cropped%29.jpg",
    },
    {
      id: "ny-rep-22",
      name: "John Mannion",
      title: "U.S. Representative",
      state: "New York",
      stateSlug: "new-york",
      chamber: "house",
      district: "22nd District",
      party: "Democratic",
      website: "https://mannion.house.gov/",
      contactUrl: "https://mannion.house.gov/contact/",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/4/4c/John_Mannion%2C_official_portrait_%28119th_Congress%29.jpg",
    },
    {
      id: "ny-rep-23",
      name: "Nick Langworthy",
      title: "U.S. Representative",
      state: "New York",
      stateSlug: "new-york",
      chamber: "house",
      district: "23rd District",
      party: "Republican",
      website: "https://langworthy.house.gov/",
      contactUrl: "https://langworthy.house.gov/contact/",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/7/71/Rep._Langworthy_Headshot_118.jpeg",
    },
    {
      id: "ny-rep-24",
      name: "Claudia Tenney",
      title: "U.S. Representative",
      state: "New York",
      stateSlug: "new-york",
      chamber: "house",
      district: "24th District",
      party: "Republican",
      website: "https://tenney.house.gov/",
      contactUrl: "https://tenney.house.gov/contact/",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/1/1f/Rep._Claudia_Tenney_official_congressional_photo.jpg",
    },
    {
      id: "ny-rep-25",
      name: "Joe Morelle",
      title: "U.S. Representative",
      state: "New York",
      stateSlug: "new-york",
      chamber: "house",
      district: "25th District",
      party: "Democratic",
      website: "https://morelle.house.gov/",
      contactUrl: "https://morelle.house.gov/contact/",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/4/4f/Joe_Morelle_118th_Congress.jpeg",
    },
    {
      id: "ny-rep-26",
      name: "Tim Kennedy",
      title: "U.S. Representative",
      state: "New York",
      stateSlug: "new-york",
      chamber: "house",
      district: "26th District",
      party: "Democratic",
      website: "https://timkennedy.house.gov/",
      contactUrl: "https://timkennedy.house.gov/contact/",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/8/87/Rep._Tim_Kennedy%27s_Official_Portrait.jpg",
    },
  ],
},
"new-jersey": {
  name: "New Jersey",
  slug: "new-jersey",
  abbreviation: "NJ",

  governor: {
    id: "nj-governor",
    name: "Governor Mikie Sherrill",
    title: "Governor",
    state: "New Jersey",
    stateSlug: "new-jersey",
    chamber: "executive",
    party: "Democratic",
    website: "https://www.nj.gov/governor/",
    contactUrl: "https://www.nj.gov/governor/contact/",
    photoUrl: "https://upload.wikimedia.org/wikipedia/commons/8/8c/Gov._Mikie_Sherril.jpg",
  },

  senators: [
    {
      id: "nj-sen-1",
      name: "Cory Booker",
      title: "U.S. Senator",
      state: "New Jersey",
      stateSlug: "new-jersey",
      chamber: "senate",
      party: "Democratic",
      website: "https://www.booker.senate.gov/",
      contactUrl: "https://www.booker.senate.gov/contact/write-to-cory",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/2/24/Cory_Booker%2C_official_portrait_%28119th_Congress%29.jpg",
    },
    {
      id: "nj-sen-2",
      name: "Andy Kim",
      title: "U.S. Senator",
      state: "New Jersey",
      stateSlug: "new-jersey",
      chamber: "senate",
      party: "Democratic",
      website: "https://www.kim.senate.gov/",
      contactUrl: "https://www.kim.senate.gov/contact/",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/9/97/Sen_Andy_Kim_118th_Congress.jpg",
    },
  ],

  representatives: [],
},
"connecticut": {
  name: "Connecticut",
  slug: "connecticut",
  abbreviation: "CT",

  governor: {
    id: "ct-governor",
    name: "Governor Ned Lamont",
    title: "Governor",
    state: "Connecticut",
    stateSlug: "connecticut",
    chamber: "executive",
    party: "Democratic",
    website: "https://portal.ct.gov/office-of-the-governor",
    contactUrl: "https://portal.ct.gov/office-of-the-governor/contact",
    photoUrl: "https://upload.wikimedia.org/wikipedia/commons/7/7b/Ned_Lamont_2023_Inauguration.png",
  },

  senators: [
    {
      id: "ct-sen-1",
      name: "Richard Blumenthal",
      title: "U.S. Senator",
      state: "Connecticut",
      stateSlug: "connecticut",
      chamber: "senate",
      party: "Democratic",
      website: "https://www.blumenthal.senate.gov/",
      contactUrl: "https://www.blumenthal.senate.gov/contact",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/2/24/Senator_Richard_BLumenthal_-_United_States_Congressional_Delegation_visit_to_Israel_on_October_22%2C_2023.jpg",
    },
    {
      id: "ct-sen-2",
      name: "Chris Murphy",
      title: "U.S. Senator",
      state: "Connecticut",
      stateSlug: "connecticut",
      chamber: "senate",
      party: "Democratic",
      website: "https://www.murphy.senate.gov/",
      contactUrl: "https://www.murphy.senate.gov/contact",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/c/ca/Chris_Murphy%2C_official_portrait%2C_113th_Congress.jpg",
    },
  ],

  representatives: [],
},
"rhode-island": {
  name: "Rhode Island",
  slug: "rhode-island",
  abbreviation: "RI",

  governor: {
    id: "ri-governor",
    name: "Governor Dan McKee",
    title: "Governor",
    state: "Rhode Island",
    stateSlug: "rhode-island",
    chamber: "executive",
    party: "Democratic",
    website: "https://governor.ri.gov/",
    contactUrl: "https://governor.ri.gov/contact",
    photoUrl: "https://upload.wikimedia.org/wikipedia/commons/1/1b/RI_Governor_Daniel_McKee.jpg",
  },

  senators: [
    {
      id: "ri-sen-1",
      name: "Jack Reed",
      title: "U.S. Senator",
      state: "Rhode Island",
      stateSlug: "rhode-island",
      chamber: "senate",
      party: "Democratic",
      website: "https://www.reed.senate.gov/",
      contactUrl: "https://www.reed.senate.gov/contact",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/f/f4/Sen._Jack_Reed_%28D-RI%29%2C_Official_Portrait%2C_119th_Congress_%281%29.jpg",
    },
    {
      id: "ri-sen-2",
      name: "Sheldon Whitehouse",
      title: "U.S. Senator",
      state: "Rhode Island",
      stateSlug: "rhode-island",
      chamber: "senate",
      party: "Democratic",
      website: "https://www.whitehouse.senate.gov/",
      contactUrl: "https://www.whitehouse.senate.gov/contact/email-sheldon",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/a/a7/Sheldon_Whitehouse%2C_official_portrait%2C_116th_congress.jpg",
    },

  ],

  representatives: [],
},
"massachusetts": {
  name: "Massachusetts",
  slug: "massachusetts",
  abbreviation: "MA",

  governor: {
    id: "ma-governor",
    name: "Governor Maura Healey",
    title: "Governor",
    state: "Massachusetts",
    stateSlug: "massachusetts",
    chamber: "executive",
    party: "Democratic",
    website: "https://www.mass.gov/orgs/office-of-the-governor",
    contactUrl: "https://www.mass.gov/forms/email-the-governors-office",
    photoUrl: "https://upload.wikimedia.org/wikipedia/commons/3/39/Maura_Healey%2C_official_portrait%2C_governor.jpg",
  },

  senators: [
    {
      id: "ma-sen-1",
      name: "Elizabeth Warren",
      title: "U.S. Senator",
      state: "Massachusetts",
      stateSlug: "massachusetts",
      chamber: "senate",
      party: "Democratic",
      website: "https://www.warren.senate.gov/",
      contactUrl: "https://www.warren.senate.gov/contact/shareyouropinion",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/5/58/Elizabeth-warren-2022_%28cropped%29.jpg",
    },
    {
      id: "ma-sen-2",
      name: "Ed Markey",
      title: "U.S. Senator",
      state: "Massachusetts",
      stateSlug: "massachusetts",
      chamber: "senate",
      party: "Democratic",
      website: "https://www.markey.senate.gov/",
      contactUrl: "https://www.markey.senate.gov/contact",
      photoUrl: "https://en.wikipedia.org/wiki/Ed_Markey#/media/File:Edward_Markey,_official_portrait,_114th_Congress.jpg",
    },

  ],

  representatives: [],
},
"maine": {
  name: "Maine",
  slug: "maine",
  abbreviation: "ME",

  governor: {
    id: "me-governor",
    name: "Governor Janet Mills",
    title: "Governor",
    state: "Maine",
    stateSlug: "maine",
    chamber: "executive",
    party: "Democratic",
    website: "https://www.maine.gov/governor/mills/",
    contactUrl: "https://www.maine.gov/governor/mills/contact",
    photoUrl: "https://upload.wikimedia.org/wikipedia/commons/a/a8/Maine_congressional_delegation_meets_with_Gov_Janet_Mills_%28cropped%29.jpg",
  },

  senators: [
    {
      id: "me-sen-1",
      name: "Susan Collins",
      title: "U.S. Senator",
      state: "Maine",
      stateSlug: "maine",
      chamber: "senate",
      party: "Republican",
      website: "https://www.collins.senate.gov/",
      contactUrl: "https://www.collins.senate.gov/contact",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/a/ae/Senator_Susan_Collins_2014_official_portrait.jpg",
    },
    {
      id: "me-sen-2",
      name: "Angus King",
      title: "U.S. Senator",
      state: "Maine",
      stateSlug: "maine",
      chamber: "senate",
      party: "Independent",
      website: "https://www.king.senate.gov/",
      contactUrl: "https://www.king.senate.gov/contact",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/a/a7/Angus_King%2C_official_portrait%2C_113th_Congress.jpg",
    },
  ],

  representatives: [],
},
"vermont": {
  name: "Vermont",
  slug: "vermont",
  abbreviation: "VT",

  governor: {
    id: "vt-governor",
    name: "Governor Phil Scott",
    title: "Governor",
    state: "Vermont",
    stateSlug: "vermont",
    chamber: "executive",
    party: "Republican",
    website: "https://governor.vermont.gov/",
    contactUrl: "https://governor.vermont.gov/contact",
    photoUrl: "https://upload.wikimedia.org/wikipedia/commons/c/cc/Phil_Scott_2019.png",
  },

  senators: [
    {
      id: "vt-sen-1",
      name: "Bernie Sanders",
      title: "U.S. Senator",
      state: "Vermont",
      stateSlug: "vermont",
      chamber: "senate",
      party: "Independent",
      website: "https://www.sanders.senate.gov/",
      contactUrl: "https://www.sanders.senate.gov/contact/",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/2/2e/Bernie_Sanders_2023.jpg",
    },
    {
      id: "vt-sen-2",
      name: "Peter Welch",
      title: "U.S. Senator",
      state: "Vermont",
      stateSlug: "vermont",
      chamber: "senate",
      party: "Democratic",
      website: "https://www.welch.senate.gov/",
      contactUrl: "https://www.welch.senate.gov/contact/",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/d/d3/Peter_Welch_official_Senate_photo.jpg",
    },
  ],

  representatives: [],
},
"new-hampshire": {
  name: "New Hampshire",
  slug: "new-hampshire",
  abbreviation: "NH",

  governor: {
    id: "nh-governor",
    name: "Governor Kelly Ayotte",
    title: "Governor",
    state: "New Hampshire",
    stateSlug: "new-hampshire",
    chamber: "executive",
    party: "Republican",
    website: "https://www.governor.nh.gov/",
    contactUrl: "https://www.governor.nh.gov/contact",
    photoUrl: "https://upload.wikimedia.org/wikipedia/commons/9/98/Governor_Kelly_Ayotte_receives_a_briefing_from_National_Guard_cyber_operators_%28cropped%29_%28cropped%29.jpg",
  },

  senators: [
    {
      id: "nh-sen-1",
      name: "Jeanne Shaheen",
      title: "U.S. Senator",
      state: "New Hampshire",
      stateSlug: "new-hampshire",
      chamber: "senate",
      party: "Democratic",
      website: "https://www.shaheen.senate.gov/",
      contactUrl: "https://www.shaheen.senate.gov/contact",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/5/52/Shaheen_Senate_Portrait.jpg",
    },
    {
      id: "nh-sen-2",
      name: "Maggie Hassan",
      title: "U.S. Senator",
      state: "New Hampshire",
      stateSlug: "new-hampshire",
      chamber: "senate",
      party: "Democratic",
      website: "https://www.hassan.senate.gov/",
      contactUrl: "https://www.hassan.senate.gov/contact",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/3/37/Maggie_Hassan%2C_official_portrait%2C_115th_Congress.jpg",
    },
    
  ],

  representatives: [],
},
"north-carolina": {
  name: "North Carolina",
  slug: "north-carolina",
  abbreviation: "NC",

  governor: {
    id: "nc-governor",
    name: "Governor Josh Stein",
    title: "Governor",
    state: "North Carolina",
    stateSlug: "north-carolina",
    chamber: "executive",
    party: "Democratic",
    website: "https://governor.nc.gov/",
    contactUrl: "https://governor.nc.gov/contact/contact-governor-stein",
    photoUrl: "https://upload.wikimedia.org/wikipedia/commons/b/bb/Josh_Stein%2C_Governor_of_North_Carolina_%28cropped%29.jpg",
  },

  senators: [
    {
      id: "nc-sen-1",
      name: "Thom Tillis",
      title: "U.S. Senator",
      state: "North Carolina",
      stateSlug: "north-carolina",
      chamber: "senate",
      party: "Republican",
      website: "https://www.tillis.senate.gov/",
      contactUrl: "https://www.tillis.senate.gov/email-me",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/0/01/Sen._Thom_Tillis_official_photo.jpg",
    },
    {
      id: "nc-sen-2",
      name: "Ted Budd",
      title: "U.S. Senator",
      state: "North Carolina",
      stateSlug: "north-carolina",
      chamber: "senate",
      party: "Republican",
      website: "https://www.budd.senate.gov/",
      contactUrl: "https://www.budd.senate.gov/contact/",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/6/67/Senator_Ted_Budd_official_portrait_%28cropped%29.jpg",
    },
  ],

  representatives: [],
},
"south-carolina": {
  name: "South Carolina",
  slug: "south-carolina",
  abbreviation: "SC",

  governor: {
    id: "sc-governor",
    name: "Governor Henry McMaster",
    title: "Governor",
    state: "South Carolina",
    stateSlug: "south-carolina",
    chamber: "executive",
    party: "Republican",
    website: "https://governor.sc.gov/",
    contactUrl: "https://governor.sc.gov/contact",
    photoUrl: "https://upload.wikimedia.org/wikipedia/commons/9/98/McMaster_In_2024.jpg",
  },

  senators: [
    {
      id: "sc-sen-1",
      name: "Lindsey Graham",
      title: "U.S. Senator",
      state: "South Carolina",
      stateSlug: "south-carolina",
      chamber: "senate",
      party: "Republican",
      website: "https://www.lgraham.senate.gov/",
      contactUrl: "https://www.lgraham.senate.gov/public/index.cfm/contact",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/8/8e/U.S._Senator_Lindsey_Graham%2C_Official_Photo%2C_113th_Congress.jpg",
    },
    {
      id: "sc-sen-2",
      name: "Tim Scott",
      title: "U.S. Senator",
      state: "South Carolina",
      stateSlug: "south-carolina",
      chamber: "senate",
      party: "Republican",
      website: "https://www.scott.senate.gov/",
      contactUrl: "https://www.scott.senate.gov/contact",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/b/bf/Tim_Scott_official_portrait.jpg",
    },
  ],

  representatives: [],
},
"georgia": {
  name: "Georgia",
  slug: "georgia",
  abbreviation: "GA",

  governor: {
    id: "ga-governor",
    name: "Governor Brian Kemp",
    title: "Governor",
    state: "Georgia",
    stateSlug: "georgia",
    chamber: "executive",
    party: "Republican",
    website: "https://gov.georgia.gov/",
    contactUrl: "https://gov.georgia.gov/contact-us",
    photoUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e8/Brian_Kemp_2023.jpg",
  },

  senators: [
    {
      id: "ga-sen-1",
      name: "Jon Ossoff",
      title: "U.S. Senator",
      state: "Georgia",
      stateSlug: "georgia",
      chamber: "senate",
      party: "Democratic",
      website: "https://www.ossoff.senate.gov/",
      contactUrl: "https://www.ossoff.senate.gov/contact-us/",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/9/97/Jon_Ossoff_Senate_Portrait_2021.jpg",
    },
    {
      id: "ga-sen-2",
      name: "Raphael Warnock",
      title: "U.S. Senator",
      state: "Georgia",
      stateSlug: "georgia",
      chamber: "senate",
      party: "Democratic",
      website: "https://www.warnock.senate.gov/",
      contactUrl: "https://www.warnock.senate.gov/contact/",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/a/a3/Raphael_Warnock_official_photo.jpg",
    },
  ],

  representatives: [],
},
"florida": {
  name: "Florida",
  slug: "florida",
  abbreviation: "FL",

  governor: {
    id: "fl-governor",
    name: "Governor Ron DeSantis",
    title: "Governor",
    state: "Florida",
    stateSlug: "florida",
    chamber: "executive",
    party: "Republican",
    website: "https://www.flgov.com/",
    contactUrl: "https://www.flgov.com/email-the-governor/",
    photoUrl: "https://upload.wikimedia.org/wikipedia/commons/4/4f/Ron_DeSantis_official_photo.jpg",
  },

  senators: [
    {
      id: "fl-sen-1",
      name: "Rick Scott",
      title: "U.S. Senator",
      state: "Florida",
      stateSlug: "florida",
      chamber: "senate",
      party: "Republican",
      website: "https://www.rickscott.senate.gov/",
      contactUrl: "https://www.rickscott.senate.gov/contact/contact",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/1/1d/Official_Portrait_of_Senator_Rick_Scott_%28R-FL%29.jpg",
    },
    {
      id: "fl-sen-2",
      name: "Ashley Moody",
      title: "U.S. Senator",
      state: "Florida",
      stateSlug: "florida",
      chamber: "senate",
      party: "Republican",
      website: "https://www.moody.senate.gov/",
      contactUrl: "https://www.moody.senate.gov/public/index.cfm/contact",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/6/6b/Senator_Ashley_Moody_Official_Portrait.jpg",
    },
  ],

  representatives: [],
},
};





export const getState = (slug: string) => stateOfficials[slug];