import { StateOfficials } from "@/lib/types";

export const stateOfficials: Record<string, StateOfficials> = {
  maryland: {
    name: "Maryland",
    slug: "maryland",
    abbreviation: "MD",
    governor: {
      id: "md-governor",
      name: "Governor Wes Moore",
      title: "Governor",
      state: "Maryland",
      stateSlug: "maryland",
      chamber: "executive",
      party: "Democratic",
      website: "https://governor.maryland.gov/",
      contactUrl: "https://governor.maryland.gov/contact-us/",
      photoUrl: "",
    },
    senators: [
      {
        id: "md-sen-1",
        name: "Chris Van Hollen",
        title: "U.S. Senator",
        state: "Maryland",
        stateSlug: "maryland",
        chamber: "senate",
        party: "Democratic",
        website: "https://www.vanhollen.senate.gov/",
        contactUrl: "https://www.vanhollen.senate.gov/contact/email",
        photoUrl: "",
      },
      {
        id: "md-sen-2",
        name: "Angela Alsobrooks",
        title: "U.S. Senator",
        state: "Maryland",
        stateSlug: "maryland",
        chamber: "senate",
        party: "Democratic",
        website: "https://www.alsobrooks.senate.gov/",
        contactUrl: "https://www.alsobrooks.senate.gov/contact/",
        photoUrl: "",
      },
    ],
    representatives: [
      {
        id: "md-rep-1",
        name: "Andy Harris",
        title: "U.S. Representative",
        state: "Maryland",
        stateSlug: "maryland",
        chamber: "house",
        district: "1st District",
        party: "Republican",
        website: "https://harris.house.gov/",
        contactUrl: "https://harris.house.gov/contact",
        photoUrl: "",
      },
      {
        id: "md-rep-2",
        name: "Johnny Olszewski",
        title: "U.S. Representative",
        state: "Maryland",
        stateSlug: "maryland",
        chamber: "house",
        district: "2nd District",
        party: "Democratic",
        website: "https://olszewski.house.gov/",
        contactUrl: "https://olszewski.house.gov/contact/",
        photoUrl: "",
      },
      {
        id: "md-rep-3",
        name: "Sarah Elfreth",
        title: "U.S. Representative",
        state: "Maryland",
        stateSlug: "maryland",
        chamber: "house",
        district: "3rd District",
        party: "Democratic",
        website: "https://elfreth.house.gov/",
        contactUrl: "https://elfreth.house.gov/address_authentication?form=/contact",
        photoUrl: "",
      },
      {
        id: "md-rep-4",
        name: "Glen Ivey",
        title: "U.S. Representative",
        state: "Maryland",
        stateSlug: "maryland",
        chamber: "house",
        district: "4th District",
        party: "Democratic",
        website: "https://ivey.house.gov/",
        contactUrl: "https://ivey.house.gov/address_authentication?form=/contact",
        photoUrl: "",
      },
      {
        id: "md-rep-5",
        name: "Steny Hoyer",
        title: "U.S. Representative",
        state: "Maryland",
        stateSlug: "maryland",
        chamber: "house",
        district: "5th District",
        party: "Democratic",
        website: "https://hoyer.house.gov/",
        contactUrl: "https://hoyer.house.gov/address_authentication?form=/contact",
        photoUrl: "",
      },
      {
        id: "md-rep-6",
        name: "April McClain Delaney",
        title: "U.S. Representative",
        state: "Maryland",
        stateSlug: "maryland",
        chamber: "house",
        district: "6th District",
        party: "Democratic",
        website: "https://mcclaindelaney.house.gov/",
        contactUrl: "https://delaney.house.gov/address_authentication?form=/contact",
        photoUrl: "",
      },
      {
        id: "md-rep-7",
        name: "Kweisi Mfume",
        title: "U.S. Representative",
        state: "Maryland",
        stateSlug: "maryland",
        chamber: "house",
        district: "7th District",
        party: "Democratic",
        website: "https://mfume.house.gov/",
        contactUrl: "https://mfume.house.gov/address_authentication?form=/contact",
        photoUrl: "",
      },
      {
        id: "md-rep-8",
        name: "Jamie Raskin",
        title: "U.S. Representative",
        state: "Maryland",
        stateSlug: "maryland",
        chamber: "house",
        district: "8td District",
        party: "Democratic",
        website: "https://raskin.house.gov/",
        contactUrl: "https://raskin.house.gov/address_authentication?form=/contact",
        photoUrl: "",
      }
    ],
  },
};