import { StateOfficials } from "@/lib/types";

export const stateOfficials: Record<string, StateOfficials> = {
  maryland: {
    name: "Maryland",
    slug: "maryland",
    abbreviation: "MD",
    governor: {
      id: "md-governor",
      name: "Governor Wes Moore",
      title: "Governor",
      state: "Maryland",
      stateSlug: "maryland",
      chamber: "executive",
      party: "Democratic",
      website: "https://governor.maryland.gov/",
      contactUrl: "https://governor.maryland.gov/contact-us/",
      photoUrl: "",
    },
    senators: [
      {
        id: "md-sen-1",
        name: "Chris Van Hollen",
        title: "U.S. Senator",
        state: "Maryland",
        stateSlug: "maryland",
        chamber: "senate",
        party: "Democratic",
        website: "https://www.vanhollen.senate.gov/",
        contactUrl: "https://www.vanhollen.senate.gov/contact/email",
        photoUrl: "",
      },
      {
        id: "md-sen-2",
        name: "Angela Alsobrooks",
        title: "U.S. Senator",
        state: "Maryland",
        stateSlug: "maryland",
        chamber: "senate",
        party: "Democratic",
        website: "https://www.alsobrooks.senate.gov/",
        contactUrl: "https://www.alsobrooks.senate.gov/contact/",
        photoUrl: "",
      },
    ],
    representatives: [
      {
        id: "md-rep-1",
        name: "Andy Harris",
        title: "U.S. Representative",
        state: "Maryland",
        stateSlug: "maryland",
        chamber: "house",
        district: "1st District",
        party: "Republican",
        website: "https://harris.house.gov/",
        contactUrl: "https://harris.house.gov/contact",
        photoUrl: "",
      },
      {
        id: "md-rep-2",
        name: "Johnny Olszewski",
        title: "U.S. Representative",
        state: "Maryland",
        stateSlug: "maryland",
        chamber: "house",
        district: "2nd District",
        party: "Democratic",
        website: "https://olszewski.house.gov/",
        contactUrl: "https://olszewski.house.gov/contact/",
        photoUrl: "",
      },
      {
        id: "md-rep-3",
        name: "Sarah Elfreth",
        title: "U.S. Representative",
        state: "Maryland",
        stateSlug: "maryland",
        chamber: "house",
        district: "3rd District",
        party: "Democratic",
        website: "https://elfreth.house.gov/",
        contactUrl: "https://elfreth.house.gov/address_authentication?form=/contact",
        photoUrl: "",
      },
      {
        id: "md-rep-4",
        name: "Glen Ivey",
        title: "U.S. Representative",
        state: "Maryland",
        stateSlug: "maryland",
        chamber: "house",
        district: "4th District",
        party: "Democratic",
        website: "https://ivey.house.gov/",
        contactUrl: "https://ivey.house.gov/address_authentication?form=/contact",
        photoUrl: "",
      },
      {
        id: "md-rep-5",
        name: "Steny Hoyer",
        title: "U.S. Representative",
        state: "Maryland",
        stateSlug: "maryland",
        chamber: "house",
        district: "5th District",
        party: "Democratic",
        website: "https://hoyer.house.gov/",
        contactUrl: "https://hoyer.house.gov/address_authentication?form=/contact",
        photoUrl: "",
      },
      {
        id: "md-rep-6",
        name: "April McClain Delaney",
        title: "U.S. Representative",
        state: "Maryland",
        stateSlug: "maryland",
        chamber: "house",
        district: "6th District",
        party: "Democratic",
        website: "https://mcclaindelaney.house.gov/",
        contactUrl: "https://delaney.house.gov/address_authentication?form=/contact",
        photoUrl: "",
      },
      {
        id: "md-rep-7",
        name: "Kweisi Mfume",
        title: "U.S. Representative",
        state: "Maryland",
        stateSlug: "maryland",
        chamber: "house",
        district: "7th District",
        party: "Democratic",
        website: "https://mfume.house.gov/",
        contactUrl: "https://mfume.house.gov/address_authentication?form=/contact",
        photoUrl: "",
      },
      {
        id: "md-rep-8",
        name: "Jamie Raskin",
        title: "U.S. Representative",
        state: "Maryland",
        stateSlug: "maryland",
        chamber: "house",
        district: "8th District",
        party: "Democratic",
        website: "https://raskin.house.gov/",
        contactUrl: "https://raskin.house.gov/address_authentication?form=/contact",
        photoUrl: "",
      }
    ],
  },
   delaware: {
    name: "Delaware",
    slug: "delaware",
    abbreviation: "DE",
    governor: {
      id: "de-governor",
      name: "Governor Matt Meyer",
      title: "Governor",
      state: "Delaware",
      stateSlug: "delaware",
      chamber: "executive",
      party: "Democratic",
      website: "https://governor.delaware.gov/",
      contactUrl: "https://governor.delaware.gov/contact/",
      photoUrl: "",
    },
    senators: [
      {
        id: "de-sen-1",
        name: "Lisa Blunt Rochester",
        title: "U.S. Senator",
        state: "Delaware",
        stateSlug: "delaware",
        chamber: "senate",
        party: "Democratic",
        website: "https://www.bluntrochester.senate.gov/",
        contactUrl: "https://www.bluntrochester.senate.gov/contact/",
        photoUrl: "",
      },
      {
        id: "de-sen-2",
        name: "Chris Coons",
        title: "U.S. Senator",
        state: "Delaware",
        stateSlug: "delaware",
        chamber: "senate",
        party: "Democratic",
        website: "https://www.coons.senate.gov/",
        contactUrl: "https://www.coons.senate.gov/contact/share-your-opinion",
        photoUrl: "",
      },
    ],
    representatives: [
      {
        id: "de-rep-at-large",
        name: "Sarah McBride",
        title: "U.S. Representative",
        state: "Delaware",
        stateSlug: "delaware",
        chamber: "house",
        district: "At-Large",
        party: "Democratic",
        website: "https://mcbride.house.gov/",
        contactUrl: "https://mcbride.house.gov/contact/",
        photoUrl: "",
      },
    ],
  },
  virginia: {
  name: "Virginia",
  slug: "virginia",
  abbreviation: "VA",

  governor: {
    id: "va-governor",
    name: "Governor Abigail Spanberger",
    title: "Governor",
    state: "Virginia",
    stateSlug: "virginia",
    chamber: "executive",
    party: "Democratic",
    website: "https://www.governor.virginia.gov/",
    contactUrl: "https://www.governor.virginia.gov/communicating-with-the-governors-office/",
    photoUrl: "",
  },

  senators: [
    {
      id: "va-sen-1",
      name: "Mark Warner",
      title: "U.S. Senator",
      state: "Virginia",
      stateSlug: "virginia",
      chamber: "senate",
      party: "Democratic",
      website: "https://www.warner.senate.gov/",
      contactUrl: "https://www.warner.senate.gov/public/index.cfm?p=Contact",
      photoUrl: "",
    },
    {
      id: "va-sen-2",
      name: "Tim Kaine",
      title: "U.S. Senator",
      state: "Virginia",
      stateSlug: "virginia",
      chamber: "senate",
      party: "Democratic",
      website: "https://www.kaine.senate.gov/",
      contactUrl: "https://www.kaine.senate.gov/contact",
      photoUrl: "",
    },
  ],

  representatives: [
    {
      id: "va-rep-1",
      name: "Rob Wittman",
      title: "U.S. Representative",
      state: "Virginia",
      stateSlug: "virginia",
      chamber: "house",
      district: "1st District",
      party: "Republican",
      website: "https://wittman.house.gov/",
      contactUrl: "https://wittman.house.gov/contact/",
      photoUrl: "",
    },
    {
      id: "va-rep-2",
      name: "Jen Kiggans",
      title: "U.S. Representative",
      state: "Virginia",
      stateSlug: "virginia",
      chamber: "house",
      district: "2nd District",
      party: "Republican",
      website: "https://kiggans.house.gov/",
      contactUrl: "https://kiggans.house.gov/contact/",
      photoUrl: "",
    },
    {
      id: "va-rep-3",
      name: "Bobby Scott",
      title: "U.S. Representative",
      state: "Virginia",
      stateSlug: "virginia",
      chamber: "house",
      district: "3rd District",
      party: "Democratic",
      website: "https://bobbyscott.house.gov/",
      contactUrl: "https://bobbyscott.house.gov/contact/",
      photoUrl: "",
    },
    {
      id: "va-rep-4",
      name: "Jennifer McClellan",
      title: "U.S. Representative",
      state: "Virginia",
      stateSlug: "virginia",
      chamber: "house",
      district: "4th District",
      party: "Democratic",
      website: "https://mcclellan.house.gov/",
      contactUrl: "https://mcclellan.house.gov/contact/",
      photoUrl: "",
    },
    {
      id: "va-rep-5",
      name: "Bob Good",
      title: "U.S. Representative",
      state: "Virginia",
      stateSlug: "virginia",
      chamber: "house",
      district: "5th District",
      party: "Republican",
      website: "https://good.house.gov/",
      contactUrl: "https://good.house.gov/contact/",
      photoUrl: "",
    },
    {
      id: "va-rep-6",
      name: "Ben Cline",
      title: "U.S. Representative",
      state: "Virginia",
      stateSlug: "virginia",
      chamber: "house",
      district: "6th District",
      party: "Republican",
      website: "https://cline.house.gov/",
      contactUrl: "https://cline.house.gov/contact/",
      photoUrl: "",
    },
    {
      id: "va-rep-7",
      name: "Eugene Vindman",
      title: "U.S. Representative",
      state: "Virginia",
      stateSlug: "virginia",
      chamber: "house",
      district: "7th District",
      party: "Democratic",
      website: "https://vindman.house.gov/",
      contactUrl: "https://vindman.house.gov/contact/",
      photoUrl: "",
    },
    {
      id: "va-rep-8",
      name: "Don Beyer",
      title: "U.S. Representative",
      state: "Virginia",
      stateSlug: "virginia",
      chamber: "house",
      district: "8th District",
      party: "Democratic",
      website: "https://beyer.house.gov/",
      contactUrl: "https://beyer.house.gov/contact/",
      photoUrl: "",
    },
    {
      id: "va-rep-9",
      name: "Morgan Griffith",
      title: "U.S. Representative",
      state: "Virginia",
      stateSlug: "virginia",
      chamber: "house",
      district: "9th District",
      party: "Republican",
      website: "https://griffith.house.gov/",
      contactUrl: "https://griffith.house.gov/contact/",
      photoUrl: "",
    },
    {
      id: "va-rep-10",
      name: "Suhas Subramanyam",
      title: "U.S. Representative",
      state: "Virginia",
      stateSlug: "virginia",
      chamber: "house",
      district: "10th District",
      party: "Democratic",
      website: "https://subramanyam.house.gov/",
      contactUrl: "https://subramanyam.house.gov/contact/",
      photoUrl: "",
    },
    {
      id: "va-rep-11",
      name: "Gerry Connolly",
      title: "U.S. Representative",
      state: "Virginia",
      stateSlug: "virginia",
      chamber: "house",
      district: "11th District",
      party: "Democratic",
      website: "https://connolly.house.gov/",
      contactUrl: "https://connolly.house.gov/contact/",
      photoUrl: "",
    },
  ],
},
};