export type AppState = {
  name: string;
  slug: string;
  abbreviation: string;
};

export const states: AppState[] = [
  { name: "Delaware", slug: "delaware", abbreviation: "DE" },
  { name: "Maryland", slug: "maryland", abbreviation: "MD" },
  { name: "Virginia", slug: "virginia", abbreviation: "VA" },
  { name: "Pennsylvania", slug: "pennsylvania", abbreviation: "PA" },
  { name: "West Virginia", slug: "west virginia", abbreviation: "WV" },
  { name: "New York", slug: "new york", abbreviation: "NY" },
  { name: "New Jersey", slug: "new jersey", abbreviation: "NJ" },
  { name: "Connecticut", slug: "connecticut", abbreviation: "CT" },
  { name: "Rhode Island", slug: "rhode Island", abbreviation: "RI" },
  { name: "Massachussetts", slug: "new york", abbreviation: "MA" },
  { name: "Maine", slug: "maine", abbreviation: "ME" },
  { name: "Vermont", slug: "vermont", abbreviation: "VT" },
  { name: "New Hampshire", slug: "new hampshire", abbreviation: "NH" },
  { name: "North Carolina", slug: "North Carolina", abbreviation: "NC" },
  { name: "South Carolina", slug: "south carolina", abbreviation: "SC" },
  { name: "Georgia", slug: "georgia", abbreviation: "GA" },
  { name: "Florida", slug: "florida", abbreviation: "FL" },
  { name: "Alabama", slug: "alabama", abbreviation: "AL" },
  { name: "Mississippi", slug: "mississippi", abbreviation: "MS" },
  { name: "Arkansas", slug: "arkansas", abbreviation: "AR" },
  { name: "Louisiana", slug: "louisiana", abbreviation: "LA" },
  { name: "Tennessee", slug: "tennessee", abbreviation: "TN" },
  { name: "Kentucky", slug: "kentucky", abbreviation: "KY" },
  { name: "Ohio", slug: "ohio", abbreviation: "OH" },
  { name: "Indiana", slug: "indiana", abbreviation: "IN" },
  { name: "Michigan", slug: "michigan", abbreviation: "MI" },
  { name: "Wisconsin", slug: "wisconsin", abbreviation: "WI" },
  { name: "Minnesota", slug: "minnesota", abbreviation: "MN" },
  { name: "Illinois", slug: "illinois", abbreviation: "IL" },
  { name: "Iowa", slug: "iowa", abbreviation: "IA" },
  { name: "Missouri", slug: "missouri", abbreviation: "MO" },
  { name: "Kansas", slug: "kansas", abbreviation: "KS" },
  { name: "Oklahoma", slug: "oklahoma", abbreviation: "OK" },
  { name: "Nebraska", slug: "nebraska", abbreviation: "NE" },
  { name: "Texas", slug: "texas", abbreviation: "TX" },
  { name: "North Dakota", slug: "north dakota", abbreviation: "ND" },
  { name: "South Dakota", slug: "south dakota", abbreviation: "SD" },
  { name: "Wyoming", slug: "wyoming", abbreviation: "WY" },
  { name: "Montana", slug: "montana", abbreviation: "MT" },
  { name: "Idaho", slug: "idaho", abbreviation: "ID" },
  { name: "Colorado", slug: "colorado", abbreviation: "CO" },
  { name: "Utah", slug: "utah", abbreviation: "UT" },
  { name: "Nevada", slug: "nevada", abbreviation: "NV" },
  { name: "New Mexico", slug: "new mexico", abbreviation: "NM" },
  { name: "Arizona", slug: "arizona", abbreviation: "AZ" },
  { name: "California", slug: "california", abbreviation: "CA" },
  { name: "Oregon", slug: "OR", abbreviation: "OR" },
  { name: "Washington", slug: "washington", abbreviation: "WA" },
  { name: "Hawaii", slug: "hawaii", abbreviation: "HI" },
  { name: "Alaska", slug: "alaska", abbreviation: "AK" },
];